name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup ROS
        uses: taka-kazu/setup-ros@pin-empy
        with:
          required-ros-distributions: noetic
      - name: Build
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros1-distro: noetic
